export const SELECT_QUIZ = "SELECT_QUIZ";
export const SEND_QUIZ_SELECTED_OPTIONS = "SEND_QUIZ_SELECTED_OPTIONS";


//User
export const POST_USER_DATA = "POST_USER_DATA";
export const USER_MESSAGE = "USER_MESSAGE"
export const USER_SINGIN = "USER_SINGIN"
export const SUBMIT_QUIZ_RESULT = "SUBMIT_QUIZ_RESULT"
export const GET_ALL_USER_RESULT_DATA ="GET_ALL_USER_RESULT_DATA"